# Generated by Django 4.2.6 on 2023-10-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_home_score', models.IntegerField()),
                ('historical_away_score', models.IntegerField()),
                ('historical_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_matches', to='app.match')),
            ],
        ),
    ]
