# Generated by Django 4.2.6 on 2023-10-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historicalmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='away_team',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalmatch',
            name='home_team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
